### PR TITLE
Improved header

### PR DESCRIPTION
**Pull request by pbihler**
Show summary & make it collapsible by double click

### CODE REVIEW

**Comment by rprieto** [comment]
The code looks great, thanks a lot for looking into this! I'll give it a try this morning and hopefully we can merge it then.

:thumbsup:

**Comment by rprieto** [comment]
ps: it seems to be built on top of #16 so let's merge the other one first.

**Comment by pbihler** [comment]
Merged fix for #16 into this as well, so they are in line

**Comment by nguyenchr** [comment]
Thanks again for your contributions

now that #16 is merged into master, are you able to rebase this branch onto master? That will get rid of the `Merge branch 'master' into summary` commit which is no longer needed

**Comment by pbihler** [comment]
Done.

**Comment by nguyenchr** [comment]
@pbihler sorry but it looks like your branch is in a bit of a weird state, I think it might have been merged, rather than rebased

can you try resetting you `summary` branch back one commit e.g. `git reset HEAD~1` then doing a force push `git push origin summary --force` , that is assuming your fork has a remote name of `origin`

**Comment by pbihler** [comment]
That looks better now :)

**Comment by nguyenchr** [comment]
@pbihler looks great!! thank alot

**Pull request merged**
