### PR TITLE
Add possibility to customize environment variables

### PR DESCRIPTION
**Pull request by fixe**
screen shot 2015-02-09 at 00 36 41

### CODE REVIEW

**Comment by nguyenchr** [comment]
Thanks alot for your PR. The code looks great

Can you please update the readme with this new option?

**Comment by fixe** [comment]
@nguyenchr done.

**Comment by rprieto** [comment]
Thanks for that, we'll publish a new version on Monday!

**Comment by fixe** [comment]
@rprieto can you please release a new version? Thanks!

**Comment by rprieto** [comment]
Sorry about that, I completely forgot! Done as `0.4.0`.

**Comment by fixe** [comment]
Thanks :-)

**Pull request merged**
